### ISSUE TITLE
Better Error message when no Pipeline is active

### ISSUE THREAD

**Issue by thaqibm** [fennel-ai/client#288]
Code:
```py

@meta(owner="xiao@fennel.ai", tags=["movie"])
@dataset
class RatingsByMovie:
    movie_id: int = field(key=True)
    avg_rating_1d: float
    avg_rating_7d: float
    timestamp: datetime = field(timestamp=True)

    @pipeline(version=1)
    @inputs(Ratings)
    def agg_ratings(cls, ratings: Dataset):
        return ratings.groupby("movie_id").aggregate(
            [
                Average(
                    of="rating",
                    window=Window("1d"),
                    into_field="avg_rating_1d",
                ),
                Average(
                    of="rating",
                    window=Window("7d"),
                    into_field="avg_rating_7d",
                ),
            ]
        )

    @pipeline(version=2)
    @inputs(Ratings)
    def agg_ratings2(cls, ratings: Dataset):
        return ratings.groupby("movie_id").aggregate(
            [
                Average(
                    of="rating",
                    window=Window("1d"),
                    into_field="avg_rating_1d",
                ),
                Average(
                    of="rating",
                    window=Window("7d"),
                    into_field="avg_rating_7d",
                ),
            ]
        )

```

The error for this is very ugly and hard to understand. I had to read another example to see why this was failing.

Error: 
```
Traceback (most recent call last):
  File "min/main.py", line 44, in <module>
    @dataset
     ^^^^^^^
  File "client/fennel/datasets/datasets.py", line 910, in dataset
    return wrap(cls)
           ^^^^^^^^^
  File "client/fennel/datasets/datasets.py", line 903, in wrap
    return _create_dataset(c, cast(Duration, history))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "client/fennel/datasets/datasets.py", line 893, in _create_dataset
    return Dataset(
           ^^^^^^^^
  File "client/fennel/datasets/datasets.py", line 1150, in __init__
    self._pipelines = self._get_pipelines()
                      ^^^^^^^^^^^^^^^^^^^^^
  File "client/fennel/datasets/datasets.py", line 1371, in _get_pipelines
    self._validate_pipelines(pipelines)
  File "client/fennel/datasets/datasets.py", line 1405, in _validate_pipelines
    raise ValueError(
```

**Comment by nikhilgarg28** [comment]
I thought the highest version pipeline was the active pipeline by default? Either way, now that I see it, I think it is probably good idea to have the following behavior:
if there is only pipeline, use that as active pipeline. If there are more than one, require active to be explicit.

**Comment by thaqibm** [comment]
> if there is only pipeline, use that as active pipeline. If there are more than one, require active to be explicit.

This is the current behavior. But in the case when the user did not set `active=True` on one of the pipelines the error message is unreadable

**Comment by thaqibm** [comment]
Current Error message says no active pipeline:

```
Traceback (most recent call last):
  File "/Users/fennelintern/dev/examples/min/main.py", line 44, in <module>
    @dataset
     ^^^^^^^
  File "/Users/fennelintern/dev/client/fennel/datasets/datasets.py", line 910, in dataset
    return wrap(cls)
           ^^^^^^^^^
  File "/Users/fennelintern/dev/client/fennel/datasets/datasets.py", line 903, in wrap
    return _create_dataset(c, cast(Duration, history))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fennelintern/dev/client/fennel/datasets/datasets.py", line 893, in _create_dataset
    return Dataset(
           ^^^^^^^^
  File "/Users/fennelintern/dev/client/fennel/datasets/datasets.py", line 1150, in __init__
    self._pipelines = self._get_pipelines()
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fennelintern/dev/client/fennel/datasets/datasets.py", line 1371, in _get_pipelines
    self._validate_pipelines(pipelines)
  File "/Users/fennelintern/dev/client/fennel/datasets/datasets.py", line 1405, in _validate_pipelines
    raise ValueError(
ValueError: No active pipeline found for dataset RatingsByMovie.
```

**Comment by nikhilgarg28** [comment]
I think we could make this error message even better by specifying how to fix this. Something along the lines of: "Dataset 'RatingsByMovie' has multiple pipelines but none is marked active. Set `@pipeline(..., active=True, ..)` on one of them or read more in docs here<link>"

Or something along these lines. cc @aditya-nambiar

**Comment by aditya-nambiar** [comment]
Closing since now there is a single pipeline per dataset
